rails/config/routes.rb
Duddycool::Application.routes.draw do

  resources :copipes

  root :to => 'copipes#index'

  match 'tags/:name' => 'tags#search'
  match 'copipes/txt/:id' => 'copipes#txt'
  match 'auth/:provider/callback', to: 'sessions#callback'
  match 'logout' => 'sessions#logout'
end

rails/app/models/copipe.rb
class Copipe < ActiveRecord::Base
  attr_accessible :body, :title
  attr_protected :user_id
  has_many :copipe_tags
  has_many :tags, :through => :copipe_tags
  belongs_to :user
  def anonymous?
    if self.user_id == 0
      return true
    end
    return false
  end
end

rails/app/models/copipe_tag.rb
class CopipeTag < ActiveRecord::Base
  attr_accessible :copipe_id, :tag_id
  belongs_to :copipe
  belongs_to :tag
end

rails/app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :copipe_tags
  has_many :copipes, :through=> :copipe_tags

end

rails/app/models/user.rb
class User < ActiveRecord::Base
  has_many :copipes
  # attr_accessible :title, :body
  def self.create_with_omniauth( auth )
    user = User.new
    user[:provider] = auth["provider"]
    user[:uid] = auth["uid"]

    unless auth["info"].blank?
      user[:name] = auth["info"]["name"]
      user[:screen_name] = auth["info"]["nickname"]
      user[:image] = auth["info"]["image"]
    end
    user.save
    return user
  end

  def self.find_from_oauth(provider, uid)
    return User.where( provider: provider, uid: uid ).first
  end
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_locale

  helper_method :current_user
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def current_user
    @current_user = User.find_by_id( session[:user_id] )
  end

  def login?
    return current_user ? true : false
  end

end

rails/app/controllers/copipes_controller.rb
# encoding: utf-8
class CopipesController < ApplicationController
  # GET /copipes
  # GET /copipes.json
  def index
    @copipes = Copipe.find(:all, :order=> 'id desc')
    respond_to do |format|
      
      format.html # index.html.erb
      format.json { render json: @copipes }
    end
  end

  # GET /copipes/1
  # GET /copipes/1.json
  def show
    @copipe = Copipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @copipe }
    end
  end


  def txt
    @copipe = Copipe.find(params[:id])
    render :layout => "empty"
  end

  # GET /copipes/new
  # GET /copipes/new.json
  def new
    @copipe = Copipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @copipe }
    end
  end
  # GET /copipes/1/edit
  #def edit
    #@copipe = Copipe.find(params[:id])
  #end

  # POST /copipes
  # POST /copipes.json
  def create
    @copipe = Copipe.new(params[:copipe])
    if login? then
      @copipe.user_id = session[:user_id]
    else
      @copipe.user_id = 0
    end
    respond_to do |format|
      if @copipe.save
        # タグ投稿
        add_tags(@copipe.id, params[:tags])
        format.html { redirect_to "/", notice: (:create_complete)}
        format.json { render json: @copipe, status: :created, location: @copipe }
      else
        format.html { render action: "new" }
        format.json { render json: @copipe.errors, status: :unprocessable_entity }
      end
    end
  end

protected
  def add_tags(copipe_id, tags)
    unless tags
      return
    end
    tags = tags.split(/[\s|　]/)
    tags = tags.uniq
    tags.each{|tag_name|
      tag = Tag.find_or_create_by_name(tag_name)
      CopipeTag.create({:copipe_id => copipe_id, :tag_id => tag.id})
    }
  end
end

rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def callback
    auth = request.env["omniauth.auth"]
    user = User.find_from_oauth( auth["provider"], auth["uid"] )
    unless user then
      user = User.create_with_omniauth( auth )
    end
    session[:user_id] = user.id
    redirect_to :root, notice: :login_complete
  end

  def logout
    session[:user_id] = nil
    redirect_to :root
  end
end

rails/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def search
    @tag = Tag.find_by_name(params[:name])
    if @tag
      @copipes = @tag.copipes
    else
      @tag = Tag.new()
      @tag.name = params[:name]
    end
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
  
end

rails/app/helpers/copipes_helper.rb
# -*- coding: utf-8 -*-

module CopipesHelper
  def format_article(text)
    # エスケープ
    text = text.dup
    text = html_escape(text)
    # 名前解析
    text = wrap_name(text)

    # div囲み
    text = text.gsub(/\r\n|\r|\n/, "<br>").html_safe
    return content_tag(:div, text, :class => "article_body")
  end

  # 名前部分を加工
  def wrap_name(text)
    name_part = extract_name(text)
    if(name_part)
      name_part_wrapped = content_tag(:span, name_part, :class => "name_2ch")
      return text.sub(name_part,name_part_wrapped )
    end
    return text
  end

  # 名前部分を特定する
  def extract_name(text)
    
    matches = /[1-9][0-9]{0,3}(\s)?(名前)?：(?<name>.+?)[\s　]?：?\s?[0-9\/]+\([月火水木金土日]\)\s[0-9:\.]+([\s[:alnum:]\/:]+)?/.match(text);
    if defined?(matches["name"]) then
      return matches["name"]
    else
      return nil
    end
  end
end

rails/app/helpers/tags_helper.rb
module TagsHelper
end

rails/app/views/copipes/_form.html.erb
<%= form_for(@copipe) do |f| %>
  <% if @copipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@copipe.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @copipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    タイトル <%= f.text_field :title %>
  </div>
  <div class="field">
    <div>本文</div>
    <div class="article_body">
      <%= f.text_area :body %>
    </div>
  </div>
  <div class="field">
    タグ
    <input name="tags" type="text" />
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

rails/app/views/copipes/_item.html.erb
<div class="copipe">
  <div class="row">
    <div class="title span6">
      No.<%= copipe.id %>
      <%= copipe.title %>
      &nbsp;
    </div>
    <div class="span4 author">
      posted by:
      <% if copipe.anonymous? %>
        <%= t(:anonymous) %>
      <% else %>
        <%= copipe.user.name %>
      <% end %>

    </div>
  </div>
  <div class="well">
    <%= format_article(copipe.body) %>
  </div>
  <div class="row">
    <div class="tags span6">
      <% if copipe.tags.count > 0 %>

        <% copipe.tags.each do |tag| %>
          <i class="icon-tags"></i>
          <%= link_to tag.name ,"/tags/"+u(tag.name) %>
        <% end %>
      <% end %>
      &nbsp;
    </div>
    <div class="span4 links">
      <i class="icon-file"></i><a href="/copipes/txt/<%= copipe.id %>">txt</a>
      <!--<i class="icon-share-alt"></i><a href="/replay/copipes">返信する</a>-->
    </div>
  </div>
</div>

rails/app/views/copipes/edit.html.erb
<h1>Editing copipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @copipe %> |
<%= link_to 'Back', copipes_path %>

rails/app/views/copipes/index.html.erb
<% @copipes.each do |copipe| %>
  <%= render :partial => "item", :locals => {:copipe => copipe} %>
<% end %>

<br />

<%= link_to 'New copipe', new_copipe_path %>

rails/app/views/copipes/new.html.erb
<h2>新規投稿</h2>

<%= render 'form' %>

<%= link_to 'Back', copipes_path %>

rails/app/views/copipes/show.html.erb
<%= render :partial=>"item" ,:locals=> {:copipe => @copipe} %>

<!--%= link_to 'Edit', edit_copipe_path(@copipe) %> | -->
<%= link_to 'Back', copipes_path %>

rails/app/views/copipes/txt.html.erb
<%= format_article(@copipe.body) %>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : t(:service_title) %></title>
    <%= csrf_meta_tags %>
    <meta name="description" content="AA共有サイト">
    <meta name="keywords" content="コピペ,2ch,２ちゃん,2ちゃんねる,まとめ,AA,アスキーアート">
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <link href="/css/bootstrap.css" media="all" rel="stylesheet" type="text/css" />
    <%= stylesheet_link_tag "application", :media => "all" %>
    <link href="/img/favicon.gif" rel="shortcut icon">
    <!--
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
    -->
    <% if Rails.env == 'production' %>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-5982830-4']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
    <% end %>
  </head>
  <body>

    <div class="navbar ">
      <div class="navbar-inner">
        <div class="container">
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><%= link_to "新規作成", "/copipes/new"  %></li>
              <li><%= link_to "一覧", "/copipes"  %></li>
            </ul>
            <ul style="float: right;" class="nav">
              <li>
                <% if current_user %>
                  <a>
                    <%= current_user.name %>
                  </a>
                <% else %>
                  <a href="/auth/twitter">
                    <%= t( :login) %>
                  </a>
                <% end %>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <h1>
        <a class="brand" href="/" ><%= t(:service_title) %></a>
        <small class="sub" >AA投稿共有サイト</small>
      </h1>
      <small><%= t(:service_title) %> は自由にAAを投稿・共有できるサイトです。(試験中)</small>
      <div class="content">
        <div class="row">
           <div class="span10">
            <% if notice %>
              <div class="alert alert-success">
                <%= t notice %>
              </div>
            <% end %>
            <% if alert %>
              <div class="alert alert-success">
                <%= t alert %>
              </div>
            <% end %>
              <%= yield %>
            </div>
            <div class="span2">
              <%= link_to "新規作成", "/copipes/new" , :class=>"btn btn-success" %>
              <% if false %>
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
              <% end %>
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <%= link_to t(:logout) , "/logout" %>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

rails/app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CopipAA" %></title>
    <%= csrf_meta_tags %>
    <meta name="description" content="コピペ・AA共有サイト">
    <meta name="keywords" content="コピペ,2ch,２ちゃん,2ちゃんねる,まとめ,AA,アスキーアート">
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <link href="/img/favicon.gif" rel="shortcut icon">
    <!--
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
    -->
    <% if Rails.env == 'production' %>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-5982830-4']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
    <% end %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

rails/app/views/tags/search.html.erb
<h2>
  <%= @tag.name %> <small>タグのついたコピペ・AA</small>
</h2>
<% if @tag.copipes %>
  <% @tag.copipes.each do |copipe| %>
    <%= render :partial => "copipes/item", :locals => {:copipe => copipe} %>
  <% end %>
<% else %>
  <%= @tag.name %>　のついたコピペ・AAはまだ投稿されていません。<br>
  よろしければ　<%= link_to '投稿', new_copipe_path , :tags => @tag.name%> していってください
<% end %>